name: Deploy to GitHub Pages

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      # This tells Gradle not to output a welcome message when it is started
      GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up JDK 21
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
        uses: actions/setup-java@v5.1.0
        with:
          java-version: "21"
          distribution: "jetbrains"
          java-package: jdk
          cache: gradle

      - name: Report Versions
        run: |
          # Output versions of OS, JDK/JVM, and Gradle
          echo "------------------------------------------------------------"
          echo "Ubuntu Linux"
          echo "------------------------------------------------------------"
          echo
          uname -a
          lsb_release -a
          echo
          echo "------------------------------------------------------------"
          echo "Open JDK"
          echo "------------------------------------------------------------"
          echo
          java -version
          # The following will also download Gradle before actually outputting its version
          ./gradlew --quiet --version

      - name: Build with Gradle
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable/

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
